version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.13.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - 9090:9090
    restart: always

  grafana:
      image: grafana/grafana:6.4.3
      depends_on:
        - prometheus
      ports:
        - 3000:3000
      volumes:
        - grafana_data:/var/lib/grafana
      restart: always

volumes:
  prometheus_data: {}
  grafana_data: {}
