version: '3'
services:
  postgres:
    image: postgres:11
    restart: always
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    #volumes:
    # - $HOME/docker/volumes/postgres:/var/lib/postgresql/
    
# docker run --rm --name pg-docker -e POSTGRES_PASSWORD=docker -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data postgres
